---
engines:
  rubocop:
    enabled: true
    channel: rubocop-1-10-0
  bundler-audit:
    enabled: true
ratings:
  paths:
  - app/**
  - config/**
  - lib/**
  - spec/**
  - test/**
  - Gemfile.lock
