language: ruby

rvm:
  - 2.6.5
  - 2.5.7
gemfile:
  - Gemfile
  - test/gemfiles/no-rails.Gemfile

sudo: false
cache:
  bundler: true

branches:
  only:
    - 'master'
    - 'develop'

before_install: gem install bundler -v 1.17.3
bundler_args: "--deployment --without development --jobs=3 --retry=3"

script: test/scripts/travis.sh
