language: ruby

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1
gemfile:
  - Gemfile
  - test/gemfiles/rails4.Gemfile
  - test/gemfiles/no-rails.Gemfile

matrix:
  exclude:
    - rvm: 2.1
      gemfile: Gemfile

sudo: false
cache:
  bundler: true

branches:
  only:
    - 'master'
    - 'develop'

before_install: gem install bundler
bundler_args: "--deployment --without development --jobs=3 --retry=3"

script: test/scripts/travis.sh
