language: ruby

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.5
  - 2.1

sudo: false
cache:
  bundler: true

branches:
  only:
    - 'master'
    - 'develop'

before_install: test/scripts/prepare-travis.sh
bundler_args: "--deployment --without development --jobs=3 --retry=3"

script: test/scripts/travis.sh
