language: ruby

rvm:
  - 2.3.1
  - 2.2.5

sudo: false
cache:
  bundler: true

branches:
  only:
    - 'master'
    - 'develop'

before_install: gem install bundler
bundler_args: "--deployment --without development --jobs=3 --retry=3"

script: bundle exec rake --trace
