name: CI
on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0
          - 2.7
        gemfile:
          - Gemfile
          - test/gemfiles/no-rails.Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      BUNDLE_WITHOUT: development
      BUNDLE_FROZEN: true
      BUNDLE_DISABLE_SHARED_GEMS: true
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: test/scripts/ci.sh
